%% -*- mode: erlang -*-
application:load(syntax_tools),
ExtraApps = case application:get_key(syntax_tools, vsn) of
                {ok, Vsn} when "1.7" > Vsn -> [merl];
                _ -> []
            end,
Apps = [kernel, stdlib, compiler, syntax_tools | ExtraApps],
[{application, erlydtl, Spec}] = CONFIG,
NewSpec = lists:keystore(applications, 1, Spec, {applications, Apps}),
[{application, erlydtl, NewSpec}].
